service: serverless-es6-async-await

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack

functions:
  jobs:
    handler: handler.jobs
    events:
      - http:
          path: /jobs
          method: get

custom:
    webpack:
      webpackConfig: 'webpack.config.js'
      includeModules: true